name: Test IDSA Postman Collections

on: [push, pull_request]

jobs:
    test_provide_data_resource_collection:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16

        - name: Install Newman
          run: npm install -g newman

        - name: Run Postman Collections
          run: newman run provide_offerings.postman_collection.json -e connector.postman_environment.json --reporters cli

    test_consume_data_resource_collection:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16

        - name: Install Newman
          run: npm install -g newman

        - name: Run Postman Collections
          run: newman run consume_offerings.postman_collection.json -e connector.postman_environment.json --reporters cli