name: Test Provide data resource collection

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collections
      run: newman run Provide data provide example data.postman_collection.json -e connector.postman_environment.json